server:
  port: 80

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/v1/api/users/**
        - id: message-service
          uri: lb://message-service
          predicates:
            - Path=/v1/api/messages/**
        - id: mail-service
          uri: lb://mail-service
          predicates:
            - Path=/v1/api/mail/**
        - id: authentication-service
          uri: lb://authentication-service
          predicates:
            - Path=/v1/api/auth/**
    config:
      uri: http://localhost:8888
      fail-fast: true
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
