server:
  port: 8080

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive  # Bu satırı ekleyin
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        - id: message-service
          uri: lb://message-service
          predicates:
            - Path=/api/messages/**
        - id: mail-service 
          uri: lb://mail-service
          predicates:
            - Path=/api/mail/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
