spring:
  application:
    name: authentication-service
  redis:
    host: 192.168.3.33
    port: 6379
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://zipkin-server:9411
    enabled: true 

resilience4j.retry:
  configs:
    default:
      maxRetryAttempts: 2
      waitDuration: 100

management:
  tracing:
    enabled: true

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    instance:
      appName: authentication-service
      prefer-ip-address: true
      ip-address: 127.0.0.1
