spring:
  application:
    name: authentication-service
  redis:
    host: 192.168.3.33
    port: 6379

resilience4j.retry:
  configs:
    default:
      maxRetryAttempts: 2
      waitDuration: 100

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    instance:
      appName: authentication-service
      prefer-ip-address: true
      ip-address: 127.0.0.1
