spring:
  application:
    name: authentication-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    instance:
      appName: authentication-service
      prefer-ip-address: true
      ip-address: 127.0.0.1
