spring:
  application:
    name: message-service
  datasource:
    url: jdbc:mysql://localhost:3307/message-service
    username: message-service
    password: plplpl123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
        deserialization:
          whitelist:
            patterns: "com.user_messaging_system.message_service.api.input.*"

server:
  port: 1080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    instance:
      appName: message-service
      prefer-ip-address: true
      ip-address: 127.0.0.1
