spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://192.168.3.33:3306/user-service
    username: user-service
    password: plplpl123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  redis:
    host: 192.168.3.33
    port: 6379

server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    instance:
      appName: user-service
      prefer-ip-address: true
      ip-address: 127.0.0.1
      
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:    
    health:
      show-details: ALWAYS

feign:
  httpclient:
    enabled: true
